# Generated by Django 5.2.8 on 2025-11-28 22:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(help_text='Documento Nacional de Identidad (7 u 8 dígitos)', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe contener entre 7 y 8 dígitos numéricos.', regex='^\\d{7,8}$')], verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(help_text='Número de contacto (10-15 dígitos)', max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener entre 10 y 15 dígitos.', regex='^\\d{10,15}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('numero_afiliado', models.CharField(blank=True, help_text='Número de obra social o prepaga', max_length=50, null=True, verbose_name='Número de Afiliado')),
                ('obra_social_id', models.CharField(blank=True, help_text='Nombre de la obra social o prepaga', max_length=100, null=True, verbose_name='Obra Social')),
                ('observaciones', models.TextField(blank=True, help_text='Alergias, antecedentes médicos, etc.', null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Paciente Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellido', 'nombre'],
                'indexes': [models.Index(fields=['dni'], name='PacientesAp_dni_49a074_idx'), models.Index(fields=['apellido', 'nombre'], name='PacientesAp_apellid_0a034f_idx')],
            },
        ),
    ]
