# Generated by Django 5.2.8 on 2026-01-30 23:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAntecedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('categoria', models.CharField(choices=[('enfermedad_cronica', 'Enfermedad Crónica'), ('its', 'Infección de Transmisión Sexual'), ('alergia', 'Alergia'), ('medicacion', 'Medicación Actual')], max_length=20, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, help_text='Información adicional sobre este antecedente', null=True, verbose_name='Descripción')),
                ('requiere_precaucion', models.BooleanField(default=False, help_text='Marca si este antecedente requiere precauciones especiales en el tratamiento', verbose_name='Requiere Precaución Especial')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Categoría de Antecedente',
                'verbose_name_plural': 'Categorías de Antecedentes',
                'ordering': ['categoria', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Obra Social')),
                ('codigo', models.CharField(blank=True, help_text='Código identificador de la obra social', max_length=20, null=True, verbose_name='Código')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Obra Social',
                'verbose_name_plural': 'Obras Sociales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(help_text='Documento Nacional de Identidad (7 u 8 dígitos)', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe contener entre 7 y 8 dígitos numéricos.', regex='^\\d{7,8}$')], verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(help_text='Número de contacto (10-15 dígitos)', max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener entre 10 y 15 dígitos.', regex='^\\d{10,15}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('numero_afiliado', models.CharField(blank=True, help_text='Número de obra social o prepaga', max_length=50, null=True, verbose_name='Número de Afiliado')),
                ('observaciones', models.TextField(blank=True, help_text='Alergias, antecedentes médicos, etc.', null=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Paciente Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('obra_social', models.ForeignKey(blank=True, help_text='Seleccione la obra social', null=True, on_delete=django.db.models.deletion.SET_NULL, to='PacientesApp.obrasocial', verbose_name='Obra Social')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AntecedentePaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones_generales', models.TextField(blank=True, help_text='Otras observaciones no categorizadas', null=True, verbose_name='Observaciones Generales')),
                ('fecha_diagnostico', models.DateField(blank=True, null=True, verbose_name='Fecha de Diagnóstico')),
                ('activo', models.BooleanField(default=True, help_text='Si el antecedente está actualmente presente', verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
                ('antecedente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PacientesApp.categoriaantecedente', verbose_name='Antecedente')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_medicos', to='PacientesApp.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Antecedente del Paciente',
                'verbose_name_plural': 'Antecedentes de los Pacientes',
                'ordering': ['-activo', 'antecedente__categoria', 'antecedente__nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['dni'], name='PacientesAp_dni_49a074_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['apellido', 'nombre'], name='PacientesAp_apellid_0a034f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='antecedentepaciente',
            unique_together={('paciente', 'antecedente')},
        ),
    ]
