# Generated by Django 5.2.8 on 2026-01-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PacientesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antecedentepaciente',
            name='observaciones_generales',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='antecedentepaciente',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Detalles específicos sobre este antecedente', null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='observaciones_generales',
            field=models.TextField(blank=True, help_text='Otras observaciones no categorizadas', null=True, verbose_name='Observaciones Generales'),
        ),
    ]
