# Generated by Django 5.2.8 on 2025-11-29 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PacientesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Obra Social')),
                ('codigo', models.CharField(blank=True, help_text='Código identificador de la obra social', max_length=20, null=True, verbose_name='Código')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Obra Social',
                'verbose_name_plural': 'Obras Sociales',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='obra_social_id',
        ),
        migrations.AddField(
            model_name='paciente',
            name='obra_social',
            field=models.ForeignKey(blank=True, help_text='Seleccione la obra social', null=True, on_delete=django.db.models.deletion.SET_NULL, to='PacientesApp.obrasocial', verbose_name='Obra Social'),
        ),
    ]
