# Generated by Django 5.2.8 on 2026-01-15 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PacientesApp', '0002_obrasocial_remove_paciente_obra_social_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAntecedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('categoria', models.CharField(choices=[('enfermedad_cronica', 'Enfermedad Crónica'), ('its', 'Infección de Transmisión Sexual'), ('alergia', 'Alergia'), ('medicacion', 'Medicación Actual')], max_length=20, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, help_text='Información adicional sobre este antecedente', null=True, verbose_name='Descripción')),
                ('requiere_precaucion', models.BooleanField(default=False, help_text='Marca si este antecedente requiere precauciones especiales en el tratamiento', verbose_name='Requiere Precaución Especial')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Categoría de Antecedente',
                'verbose_name_plural': 'Categorías de Antecedentes',
                'ordering': ['categoria', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AntecedentePaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones_generales', models.TextField(blank=True, help_text='Otras observaciones no categorizadas', null=True, verbose_name='Observaciones Generales')),
                ('fecha_diagnostico', models.DateField(blank=True, null=True, verbose_name='Fecha de Diagnóstico')),
                ('activo', models.BooleanField(default=True, help_text='Si el antecedente está actualmente presente', verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_medicos', to='PacientesApp.paciente', verbose_name='Paciente')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
                ('antecedente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PacientesApp.categoriaantecedente', verbose_name='Antecedente')),
            ],
            options={
                'verbose_name': 'Antecedente del Paciente',
                'verbose_name_plural': 'Antecedentes de los Pacientes',
                'ordering': ['-activo', 'antecedente__categoria', 'antecedente__nombre'],
                'unique_together': {('paciente', 'antecedente')},
            },
        ),
    ]
