# Generated by Django 5.2.8 on 2026-02-27 14:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PacientesApp', '0002_remove_antecedentepaciente_observaciones_generales_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('hora_inicio', models.TimeField(blank=True, help_text='Dejá vacío para bloquear todo el día', null=True, verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(blank=True, help_text='Dejá vacío para bloquear todo el día', null=True, verbose_name='Hora de Fin')),
                ('tipo', models.CharField(choices=[('feriado', 'Feriado'), ('vacaciones', 'Vacaciones'), ('ausencia', 'Ausencia'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de Bloqueo')),
                ('motivo', models.CharField(help_text='Ej: Feriado Nacional, Vacaciones de verano, Capacitación, etc.', max_length=200, verbose_name='Motivo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('odontologo', models.ForeignKey(blank=True, help_text='Dejá vacío para bloqueo general (afecta a todos)', limit_choices_to={'rol': 'odontologo'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_horario', to=settings.AUTH_USER_MODEL, verbose_name='Odontólogo')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
            ],
            options={
                'verbose_name': 'Bloqueo de Horario',
                'verbose_name_plural': 'Bloqueos de Horarios',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('duracion_turno', models.IntegerField(default=30, help_text='Entre 15 y 120 minutos', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)], verbose_name='Duración del Turno (minutos)')),
                ('turnos_simultaneos', models.IntegerField(default=1, help_text='Cantidad de pacientes que puede atender al mismo tiempo', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Turnos Simultáneos')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('odontologo', models.ForeignKey(limit_choices_to={'rol': 'odontologo'}, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_agenda', to=settings.AUTH_USER_MODEL, verbose_name='Odontólogo')),
            ],
            options={
                'verbose_name': 'Configuración de Agenda',
                'verbose_name_plural': 'Configuraciones de Agenda',
                'ordering': ['odontologo', 'dia_semana', 'hora_inicio'],
                'unique_together': {('odontologo', 'dia_semana', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del Turno')),
                ('hora', models.TimeField(verbose_name='Hora del Turno')),
                ('duracion', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)], verbose_name='Duración (minutos)')),
                ('motivo_consulta', models.CharField(help_text='Descripción breve del motivo de la consulta', max_length=255, verbose_name='Motivo de Consulta')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_atencion', 'En Atención'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado'), ('ausente', 'Paciente Ausente')], default='pendiente', max_length=20, verbose_name='Estado del Turno')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el turno', null=True, verbose_name='Observaciones')),
                ('recordatorio_enviado', models.BooleanField(default=False, help_text='Indica si se envió recordatorio al paciente', verbose_name='Recordatorio Enviado')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Atención Real')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('odontologo', models.ForeignKey(limit_choices_to={'rol': 'odontologo'}, on_delete=django.db.models.deletion.CASCADE, related_name='turnos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Odontólogo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='PacientesApp.paciente', verbose_name='Paciente')),
                ('usuario_registro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha', 'hora'],
                'indexes': [models.Index(fields=['fecha', 'hora'], name='TurnosApp_t_fecha_f16a3d_idx'), models.Index(fields=['odontologo', 'fecha'], name='TurnosApp_t_odontol_b2c003_idx'), models.Index(fields=['paciente', 'fecha'], name='TurnosApp_t_pacient_914269_idx')],
            },
        ),
    ]
